3 page de liste des écoles
iia-tawfiq/ecoles-informatique-laval pull request #39
Opened 2024-06-13 13:59 UTC by Aiizon

schools enumeration page, with filter search

2024-06-13 14:32 UTC, tawfiqct requested changes

2024-06-13 14:32 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Views/School/index.cshtml
> +                <td>@school.City</td>
Est-ce que tu pourrais faire le lien en TagHelper vers l'école

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Views/Shared/_Layout.cshtml
Ne push pas les modifications sur le Layout stp

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/wwwroot/js/schoolsSearch.js
Ne sert à rien

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Data/ApplicationDbContext.cs
Discard ces changements

2024-06-14 07:09 UTC, tawfiqct commented on README.md
Discard ces changements

2024-06-14 07:09 UTC, tawfiqct commented on README.md
Ne doit pas modifier le README

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Views/Shared/_Layout.cshtml
Quelqu'un d'autre fera tout le menu

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Data/Migrations/ApplicationDbContextModelSnapshot.cs
Ne doit pas être supprimé

2024-06-14 07:09 UTC, tawfiqct commented on ecoles-informatiques/ecoles-informatiques/Data/ApplicationDbContext.cs
Enlève cette modification

2024-06-14 07:32 UTC, tawfiqct approved these changes

2024-06-14 08:08 UTC, TYrueouJeL approved these changes
🤌

2024-06-14 08:10 UTC, natibi53 approved these changes

2024-06-14 08:27 UTC, merged