Parameters table
iia-tawfiq/ecoles-informatique-laval pull request #41
Opened 2024-06-13 14:53 UTC by Lucasfsev

2024-06-13 14:58 UTC, Aiizon requested changes

2024-06-13 14:58 UTC, Aiizon commented on ecoles-informatiques/ecoles-informatiques/Data/Migrations/20240613144633_AddParameterTable.cs
je ne vois pas la nouvelle table dans la migration, donc je suis pas sûr que ça fonctionne

2024-06-13 14:58 UTC, Aiizon commented on ecoles-informatiques/ecoles-informatiques/Models/Parameter.cs
ça ne respecte pas le schéma key => value

2024-06-14 07:12 UTC, tawfiqct requested changes
Il faut un champ Key et un champ Value

2024-06-14 08:06 UTC, closed without merging